/**
 * Fallback mock data used when the Jikan API / MyAnimeList is unavailable.
 * This keeps the platform functional for portfolio demonstration purposes.
 */

const mockAnimeList = [
  {
    mal_id: 1,
    title: 'Cowboy Bebop',
    title_english: 'Cowboy Bebop',
    title_japanese: 'カウボーイビバップ',
    type: 'TV',
    episodes: 26,
    status: 'Finished Airing',
    score: 8.75,
    scored_by: 900000,
    rank: 28,
    popularity: 39,
    members: 1800000,
    synopsis: 'In the year 2071, humanity has colonized several of the planets and moons of the solar system leaving the now uninhabitable surface of planet Earth behind. The Inter Solar System Police attempts to keep peace in the galaxy, aided in part by outlaw bounty hunters, referred to as "Cowboys."',
    season: 'spring',
    year: 1998,
    rating: 'R - 17+ (violence & profanity)',
    source: 'Original',
    duration: '24 min per ep',
    images: {
      jpg: {
        image_url: 'https://cdn.myanimelist.net/images/anime/4/19644.jpg',
        large_image_url: 'https://cdn.myanimelist.net/images/anime/4/19644l.jpg',
      },
    },
    trailer: { url: 'https://www.youtube.com/watch?v=qig4KOK2R2g' },
    genres: [
      { mal_id: 1, name: 'Action' },
      { mal_id: 24, name: 'Sci-Fi' },
    ],
    studios: [{ mal_id: 14, name: 'Sunrise' }],
  },
  {
    mal_id: 5114,
    title: 'Fullmetal Alchemist: Brotherhood',
    title_english: 'Fullmetal Alchemist: Brotherhood',
    title_japanese: '鋼の錬金術師 FULLMETAL ALCHEMIST',
    type: 'TV',
    episodes: 64,
    status: 'Finished Airing',
    score: 9.1,
    scored_by: 2100000,
    rank: 1,
    popularity: 3,
    members: 3200000,
    synopsis: 'After a horrific alchemy experiment goes wrong in the Elric household, brothers Edward and Alphonse are left in a catastrophic new reality.',
    season: 'spring',
    year: 2009,
    rating: 'R - 17+ (violence & profanity)',
    source: 'Manga',
    duration: '24 min per ep',
    images: {
      jpg: {
        image_url: 'https://cdn.myanimelist.net/images/anime/1208/94745.jpg',
        large_image_url: 'https://cdn.myanimelist.net/images/anime/1208/94745l.jpg',
      },
    },
    trailer: { url: 'https://www.youtube.com/watch?v=--IcmZkvL0Q' },
    genres: [
      { mal_id: 1, name: 'Action' },
      { mal_id: 2, name: 'Adventure' },
      { mal_id: 8, name: 'Drama' },
      { mal_id: 10, name: 'Fantasy' },
    ],
    studios: [{ mal_id: 4, name: 'Bones' }],
  },
  {
    mal_id: 1535,
    title: 'Death Note',
    title_english: 'Death Note',
    title_japanese: 'デスノート',
    type: 'TV',
    episodes: 37,
    status: 'Finished Airing',
    score: 8.62,
    scored_by: 2400000,
    rank: 75,
    popularity: 1,
    members: 3800000,
    synopsis: 'A shinigami, as a god of death, can kill any person—provided they see their victim\'s face and write their victim\'s name in a notebook called a Death Note.',
    season: 'fall',
    year: 2006,
    rating: 'R - 17+ (violence & profanity)',
    source: 'Manga',
    duration: '23 min per ep',
    images: {
      jpg: {
        image_url: 'https://cdn.myanimelist.net/images/anime/9/9453.jpg',
        large_image_url: 'https://cdn.myanimelist.net/images/anime/9/9453l.jpg',
      },
    },
    trailer: { url: 'https://www.youtube.com/watch?v=NlJZ-YgAt-c' },
    genres: [
      { mal_id: 37, name: 'Supernatural' },
      { mal_id: 7, name: 'Mystery' },
      { mal_id: 41, name: 'Suspense' },
    ],
    studios: [{ mal_id: 11, name: 'Madhouse' }],
  },
  {
    mal_id: 16498,
    title: 'Shingeki no Kyojin',
    title_english: 'Attack on Titan',
    title_japanese: '進撃の巨人',
    type: 'TV',
    episodes: 25,
    status: 'Finished Airing',
    score: 8.54,
    scored_by: 2200000,
    rank: 104,
    popularity: 2,
    members: 3700000,
    synopsis: 'Centuries ago, mankind was slaughtered to near extinction by monstrous humanoid creatures called Titans, forcing humans to hide in fear behind enormous concentric walls.',
    season: 'spring',
    year: 2013,
    rating: 'R - 17+ (violence & profanity)',
    source: 'Manga',
    duration: '24 min per ep',
    images: {
      jpg: {
        image_url: 'https://cdn.myanimelist.net/images/anime/10/47347.jpg',
        large_image_url: 'https://cdn.myanimelist.net/images/anime/10/47347l.jpg',
      },
    },
    trailer: { url: 'https://www.youtube.com/watch?v=LHtdKWJdif4' },
    genres: [
      { mal_id: 1, name: 'Action' },
      { mal_id: 8, name: 'Drama' },
      { mal_id: 41, name: 'Suspense' },
    ],
    studios: [{ mal_id: 858, name: 'Wit Studio' }],
  },
  {
    mal_id: 11757,
    title: 'Sword Art Online',
    title_english: 'Sword Art Online',
    title_japanese: 'ソードアート・オンライン',
    type: 'TV',
    episodes: 25,
    status: 'Finished Airing',
    score: 7.2,
    scored_by: 1500000,
    rank: 2500,
    popularity: 5,
    members: 2900000,
    synopsis: 'In the year 2022, virtual reality has progressed by leaps and bounds, and a massive online role-playing game called Sword Art Online (SAO) is launched.',
    season: 'summer',
    year: 2012,
    rating: 'PG-13 - Teens 13 or older',
    source: 'Light novel',
    duration: '23 min per ep',
    images: {
      jpg: {
        image_url: 'https://cdn.myanimelist.net/images/anime/11/39717.jpg',
        large_image_url: 'https://cdn.myanimelist.net/images/anime/11/39717l.jpg',
      },
    },
    trailer: { url: 'https://www.youtube.com/watch?v=6ohYYtxfDCg' },
    genres: [
      { mal_id: 1, name: 'Action' },
      { mal_id: 2, name: 'Adventure' },
      { mal_id: 10, name: 'Fantasy' },
      { mal_id: 22, name: 'Romance' },
    ],
    studios: [{ mal_id: 56, name: 'A-1 Pictures' }],
  },
  {
    mal_id: 21,
    title: 'One Punch Man',
    title_english: 'One-Punch Man',
    title_japanese: 'ワンパンマン',
    type: 'TV',
    episodes: 12,
    status: 'Finished Airing',
    score: 8.5,
    scored_by: 1700000,
    rank: 120,
    popularity: 8,
    members: 2600000,
    synopsis: 'The seemingly ordinary and unimpressive Saitama has a rather unique hobby: being a hero. In order to pursue his childhood dream, he trained relentlessly for three years.',
    season: 'fall',
    year: 2015,
    rating: 'PG-13 - Teens 13 or older',
    source: 'Web manga',
    duration: '24 min per ep',
    images: {
      jpg: {
        image_url: 'https://cdn.myanimelist.net/images/anime/12/76049.jpg',
        large_image_url: 'https://cdn.myanimelist.net/images/anime/12/76049l.jpg',
      },
    },
    trailer: { url: 'https://www.youtube.com/watch?v=A3Jks90zaEE' },
    genres: [
      { mal_id: 1, name: 'Action' },
      { mal_id: 4, name: 'Comedy' },
    ],
    studios: [{ mal_id: 11, name: 'Madhouse' }],
  },
  {
    mal_id: 20,
    title: 'Naruto',
    title_english: 'Naruto',
    title_japanese: 'ナルト',
    type: 'TV',
    episodes: 220,
    status: 'Finished Airing',
    score: 8.0,
    scored_by: 1800000,
    rank: 500,
    popularity: 7,
    members: 2700000,
    synopsis: 'Moments prior to Naruto Uzumaki\'s birth, a huge demon known as the Kyuubi, the Nine-Tailed Fox, attacked Konohagakure, the Hidden Leaf Village, and wreaked havoc.',
    season: 'fall',
    year: 2002,
    rating: 'PG-13 - Teens 13 or older',
    source: 'Manga',
    duration: '23 min per ep',
    images: {
      jpg: {
        image_url: 'https://cdn.myanimelist.net/images/anime/13/17405.jpg',
        large_image_url: 'https://cdn.myanimelist.net/images/anime/13/17405l.jpg',
      },
    },
    trailer: { url: 'https://www.youtube.com/watch?v=jMKPpiQ4TBo' },
    genres: [
      { mal_id: 1, name: 'Action' },
      { mal_id: 2, name: 'Adventure' },
      { mal_id: 10, name: 'Fantasy' },
    ],
    studios: [{ mal_id: 1, name: 'Studio Pierrot' }],
  },
  {
    mal_id: 1735,
    title: 'Naruto: Shippuuden',
    title_english: 'Naruto Shippuden',
    title_japanese: 'ナルト- 疾風伝',
    type: 'TV',
    episodes: 500,
    status: 'Finished Airing',
    score: 8.27,
    scored_by: 1400000,
    rank: 200,
    popularity: 6,
    members: 2800000,
    synopsis: 'It has been two and a half years since Naruto Uzumaki left Konohagakure, the Hidden Leaf Village, for intense training following events which fueled his desire to be stronger.',
    season: 'winter',
    year: 2007,
    rating: 'PG-13 - Teens 13 or older',
    source: 'Manga',
    duration: '23 min per ep',
    images: {
      jpg: {
        image_url: 'https://cdn.myanimelist.net/images/anime/5/17407.jpg',
        large_image_url: 'https://cdn.myanimelist.net/images/anime/5/17407l.jpg',
      },
    },
    trailer: { url: 'https://www.youtube.com/watch?v=1dy2zME32u0' },
    genres: [
      { mal_id: 1, name: 'Action' },
      { mal_id: 2, name: 'Adventure' },
      { mal_id: 10, name: 'Fantasy' },
    ],
    studios: [{ mal_id: 1, name: 'Studio Pierrot' }],
  },
  {
    mal_id: 9253,
    title: 'Steins;Gate',
    title_english: 'Steins;Gate',
    title_japanese: 'シュタインズ・ゲート',
    type: 'TV',
    episodes: 24,
    status: 'Finished Airing',
    score: 9.07,
    scored_by: 1200000,
    rank: 3,
    popularity: 13,
    members: 2400000,
    synopsis: 'The self-proclaimed mad scientist Rintarou Okabe rents out a room in a decrepit old building in Akihabara, where he indulges himself in his hobby of inventing prospective "future gadgets."',
    season: 'spring',
    year: 2011,
    rating: 'PG-13 - Teens 13 or older',
    source: 'Visual novel',
    duration: '24 min per ep',
    images: {
      jpg: {
        image_url: 'https://cdn.myanimelist.net/images/anime/5/73199.jpg',
        large_image_url: 'https://cdn.myanimelist.net/images/anime/5/73199l.jpg',
      },
    },
    trailer: { url: 'https://www.youtube.com/watch?v=27OZc-ku6is' },
    genres: [
      { mal_id: 8, name: 'Drama' },
      { mal_id: 24, name: 'Sci-Fi' },
      { mal_id: 41, name: 'Suspense' },
    ],
    studios: [{ mal_id: 314, name: 'White Fox' }],
  },
  {
    mal_id: 38000,
    title: 'Kimetsu no Yaiba',
    title_english: 'Demon Slayer: Kimetsu no Yaiba',
    title_japanese: '鬼滅の刃',
    type: 'TV',
    episodes: 26,
    status: 'Finished Airing',
    score: 8.45,
    scored_by: 1600000,
    rank: 140,
    popularity: 4,
    members: 3100000,
    synopsis: 'Ever since the death of his father, the burden of supporting the family has fallen upon Tanjirou Kamado\'s shoulders. Though living impoverished on a remote mountain, the Kamado family are able to enjoy a relatively peaceful and happy life.',
    season: 'spring',
    year: 2019,
    rating: 'R - 17+ (violence & profanity)',
    source: 'Manga',
    duration: '23 min per ep',
    images: {
      jpg: {
        image_url: 'https://cdn.myanimelist.net/images/anime/1286/99889.jpg',
        large_image_url: 'https://cdn.myanimelist.net/images/anime/1286/99889l.jpg',
      },
    },
    trailer: { url: 'https://www.youtube.com/watch?v=VQGCKyvzIM4' },
    genres: [
      { mal_id: 1, name: 'Action' },
      { mal_id: 10, name: 'Fantasy' },
    ],
    studios: [{ mal_id: 43, name: 'ufotable' }],
  },
  {
    mal_id: 21,
    title: 'One Piece',
    title_english: 'One Piece',
    title_japanese: 'ワンピース',
    type: 'TV',
    episodes: null,
    status: 'Currently Airing',
    score: 8.72,
    scored_by: 1300000,
    rank: 30,
    popularity: 10,
    members: 2500000,
    synopsis: 'Gol D. Roger was known as the "Pirate King," the strongest and most infamous being to have sailed the Grand Line.',
    season: 'fall',
    year: 1999,
    rating: 'PG-13 - Teens 13 or older',
    source: 'Manga',
    duration: '24 min',
    images: {
      jpg: {
        image_url: 'https://cdn.myanimelist.net/images/anime/6/73245.jpg',
        large_image_url: 'https://cdn.myanimelist.net/images/anime/6/73245l.jpg',
      },
    },
    trailer: { url: 'https://www.youtube.com/watch?v=MCb13lbVGE0' },
    genres: [
      { mal_id: 1, name: 'Action' },
      { mal_id: 2, name: 'Adventure' },
      { mal_id: 10, name: 'Fantasy' },
    ],
    studios: [{ mal_id: 18, name: 'Toei Animation' }],
  },
  {
    mal_id: 30276,
    title: 'One Punch Man 2nd Season',
    title_english: 'One-Punch Man Season 2',
    title_japanese: 'ワンパンマン 2',
    type: 'TV',
    episodes: 12,
    status: 'Finished Airing',
    score: 7.43,
    scored_by: 800000,
    rank: 2000,
    popularity: 35,
    members: 1900000,
    synopsis: 'In the wake of defeating Boros and his mighty army, Saitama has returned to his unremarkable everyday life in Z-City.',
    season: 'spring',
    year: 2019,
    rating: 'PG-13 - Teens 13 or older',
    source: 'Web manga',
    duration: '23 min per ep',
    images: {
      jpg: {
        image_url: 'https://cdn.myanimelist.net/images/anime/1247/122044.jpg',
        large_image_url: 'https://cdn.myanimelist.net/images/anime/1247/122044l.jpg',
      },
    },
    trailer: { url: 'https://www.youtube.com/watch?v=v1mi_kIBYS8' },
    genres: [
      { mal_id: 1, name: 'Action' },
      { mal_id: 4, name: 'Comedy' },
    ],
    studios: [{ mal_id: 7, name: 'J.C.Staff' }],
  },
  {
    mal_id: 40748,
    title: 'Jujutsu Kaisen',
    title_english: 'Jujutsu Kaisen',
    title_japanese: '呪術廻戦',
    type: 'TV',
    episodes: 24,
    status: 'Finished Airing',
    score: 8.6,
    scored_by: 1400000,
    rank: 80,
    popularity: 9,
    members: 2500000,
    synopsis: 'Idly indulging in baseless paranormal activities with the Occult Club, high schooler Yuuji Itadori spends his days at either the clubroom or the hospital, where he visits his bedridden grandfather.',
    season: 'fall',
    year: 2020,
    rating: 'R - 17+ (violence & profanity)',
    source: 'Manga',
    duration: '23 min per ep',
    images: {
      jpg: {
        image_url: 'https://cdn.myanimelist.net/images/anime/1171/109222.jpg',
        large_image_url: 'https://cdn.myanimelist.net/images/anime/1171/109222l.jpg',
      },
    },
    trailer: { url: 'https://www.youtube.com/watch?v=pkKu9hLT-t8' },
    genres: [
      { mal_id: 1, name: 'Action' },
      { mal_id: 10, name: 'Fantasy' },
    ],
    studios: [{ mal_id: 569, name: 'MAPPA' }],
  },
  {
    mal_id: 44511,
    title: 'Chainsaw Man',
    title_english: 'Chainsaw Man',
    title_japanese: 'チェンソーマン',
    type: 'TV',
    episodes: 12,
    status: 'Finished Airing',
    score: 8.44,
    scored_by: 900000,
    rank: 145,
    popularity: 15,
    members: 2300000,
    synopsis: 'Denji has a simple dream—to live a happy and peaceful life, spending time with a girl he likes. This is a far cry from reality, however, as Denji is forced by the yakuza into killing devils.',
    season: 'fall',
    year: 2022,
    rating: 'R - 17+ (violence & profanity)',
    source: 'Manga',
    duration: '24 min per ep',
    images: {
      jpg: {
        image_url: 'https://cdn.myanimelist.net/images/anime/1806/126216.jpg',
        large_image_url: 'https://cdn.myanimelist.net/images/anime/1806/126216l.jpg',
      },
    },
    trailer: { url: 'https://www.youtube.com/watch?v=q15CRdE5Bv0' },
    genres: [
      { mal_id: 1, name: 'Action' },
      { mal_id: 10, name: 'Fantasy' },
    ],
    studios: [{ mal_id: 569, name: 'MAPPA' }],
  },
  {
    mal_id: 5,
    title: 'Cowboy Bebop: Tengoku no Tobira',
    title_english: 'Cowboy Bebop: The Movie',
    title_japanese: 'カウボーイビバップ 天国の扉',
    type: 'Movie',
    episodes: 1,
    status: 'Finished Airing',
    score: 8.38,
    scored_by: 300000,
    rank: 170,
    popularity: 200,
    members: 500000,
    synopsis: 'Another day, another bounty—such is the life of the often unlucky crew of the Bebop. However, this time they get more than they bargained for.',
    season: null,
    year: 2001,
    rating: 'R - 17+ (violence & profanity)',
    source: 'Original',
    duration: '1 hr. 55 min.',
    images: {
      jpg: {
        image_url: 'https://cdn.myanimelist.net/images/anime/1439/93480.jpg',
        large_image_url: 'https://cdn.myanimelist.net/images/anime/1439/93480l.jpg',
      },
    },
    trailer: { url: null },
    genres: [
      { mal_id: 1, name: 'Action' },
      { mal_id: 24, name: 'Sci-Fi' },
    ],
    studios: [{ mal_id: 4, name: 'Bones' }],
  },
  {
    mal_id: 31964,
    title: 'Boku no Hero Academia',
    title_english: 'My Hero Academia',
    title_japanese: '僕のヒーローアカデミア',
    type: 'TV',
    episodes: 13,
    status: 'Finished Airing',
    score: 8.0,
    scored_by: 1400000,
    rank: 490,
    popularity: 11,
    members: 2400000,
    synopsis: 'The appearance of "quirks," newly discovered super powers, has been steadily increasing over the years, with 80 percent of humanity possessing various abilities from manipulation of elements to shapeshifting.',
    season: 'spring',
    year: 2016,
    rating: 'PG-13 - Teens 13 or older',
    source: 'Manga',
    duration: '24 min per ep',
    images: {
      jpg: {
        image_url: 'https://cdn.myanimelist.net/images/anime/10/78745.jpg',
        large_image_url: 'https://cdn.myanimelist.net/images/anime/10/78745l.jpg',
      },
    },
    trailer: { url: 'https://www.youtube.com/watch?v=D5fYOnwYkj4' },
    genres: [
      { mal_id: 1, name: 'Action' },
    ],
    studios: [{ mal_id: 4, name: 'Bones' }],
  },
  {
    mal_id: 11061,
    title: 'Hunter x Hunter (2011)',
    title_english: 'Hunter x Hunter',
    title_japanese: 'ハンター×ハンター (2011)',
    type: 'TV',
    episodes: 148,
    status: 'Finished Airing',
    score: 9.04,
    scored_by: 1200000,
    rank: 5,
    popularity: 12,
    members: 2400000,
    synopsis: 'Hunter x Hunter is set in a world where Hunters exist to perform all manner of dangerous tasks like capturing criminals and bravely searching for lost treasures in uncharted territories.',
    season: 'fall',
    year: 2011,
    rating: 'PG-13 - Teens 13 or older',
    source: 'Manga',
    duration: '23 min per ep',
    images: {
      jpg: {
        image_url: 'https://cdn.myanimelist.net/images/anime/1337/99013.jpg',
        large_image_url: 'https://cdn.myanimelist.net/images/anime/1337/99013l.jpg',
      },
    },
    trailer: { url: 'https://www.youtube.com/watch?v=d6kBeJjTGnY' },
    genres: [
      { mal_id: 1, name: 'Action' },
      { mal_id: 2, name: 'Adventure' },
      { mal_id: 10, name: 'Fantasy' },
    ],
    studios: [{ mal_id: 11, name: 'Madhouse' }],
  },
  {
    mal_id: 30,
    title: 'Neon Genesis Evangelion',
    title_english: 'Neon Genesis Evangelion',
    title_japanese: '新世紀エヴァンゲリオン',
    type: 'TV',
    episodes: 26,
    status: 'Finished Airing',
    score: 8.35,
    scored_by: 900000,
    rank: 180,
    popularity: 25,
    members: 2000000,
    synopsis: 'In the year 2015, the world stands on the brink of destruction. Humanity\'s last hope lies in the hands of Nerv, a special agency under the United Nations.',
    season: 'fall',
    year: 1995,
    rating: 'PG-13 - Teens 13 or older',
    source: 'Original',
    duration: '24 min per ep',
    images: {
      jpg: {
        image_url: 'https://cdn.myanimelist.net/images/anime/1314/108941.jpg',
        large_image_url: 'https://cdn.myanimelist.net/images/anime/1314/108941l.jpg',
      },
    },
    trailer: { url: null },
    genres: [
      { mal_id: 1, name: 'Action' },
      { mal_id: 5, name: 'Avant Garde' },
      { mal_id: 8, name: 'Drama' },
      { mal_id: 24, name: 'Sci-Fi' },
    ],
    studios: [{ mal_id: 6, name: 'Gainax' }],
  },
  {
    mal_id: 48583,
    title: 'Spy x Family',
    title_english: 'SPY x FAMILY',
    title_japanese: 'スパイファミリー',
    type: 'TV',
    episodes: 12,
    status: 'Finished Airing',
    score: 8.53,
    scored_by: 800000,
    rank: 110,
    popularity: 18,
    members: 2100000,
    synopsis: 'Spy, assassin, and telepath — a found family bands together to protect world peace. Master spy Twilight must build a fake family for his latest mission.',
    season: 'spring',
    year: 2022,
    rating: 'PG-13 - Teens 13 or older',
    source: 'Manga',
    duration: '24 min per ep',
    images: {
      jpg: {
        image_url: 'https://cdn.myanimelist.net/images/anime/1441/122795.jpg',
        large_image_url: 'https://cdn.myanimelist.net/images/anime/1441/122795l.jpg',
      },
    },
    trailer: { url: 'https://www.youtube.com/watch?v=ofXigq9sYAM' },
    genres: [
      { mal_id: 1, name: 'Action' },
      { mal_id: 4, name: 'Comedy' },
    ],
    studios: [{ mal_id: 858, name: 'Wit Studio' }, { mal_id: 1591, name: 'CloverWorks' }],
  },
  {
    mal_id: 50265,
    title: 'Solo Leveling',
    title_english: 'Solo Leveling',
    title_japanese: '俺だけレベルアップな件',
    type: 'TV',
    episodes: 12,
    status: 'Finished Airing',
    score: 8.21,
    scored_by: 600000,
    rank: 260,
    popularity: 22,
    members: 1800000,
    synopsis: 'In a world where hunters — human warriors who possess magical abilities — must battle deadly monsters to protect the human race from certain annihilation, a weak hunter named Sung Jinwoo finds himself in a seemingly endless struggle for survival.',
    season: 'winter',
    year: 2024,
    rating: 'R - 17+ (violence & profanity)',
    source: 'Web novel',
    duration: '23 min per ep',
    images: {
      jpg: {
        image_url: 'https://cdn.myanimelist.net/images/anime/1314/138840.jpg',
        large_image_url: 'https://cdn.myanimelist.net/images/anime/1314/138840l.jpg',
      },
    },
    trailer: { url: 'https://www.youtube.com/watch?v=UfHfBbLRMIQ' },
    genres: [
      { mal_id: 1, name: 'Action' },
      { mal_id: 10, name: 'Fantasy' },
    ],
    studios: [{ mal_id: 56, name: 'A-1 Pictures' }],
  },
];

const mockGenres = [
  { mal_id: 1, name: 'Action', count: 5000 },
  { mal_id: 2, name: 'Adventure', count: 4000 },
  { mal_id: 4, name: 'Comedy', count: 7000 },
  { mal_id: 8, name: 'Drama', count: 3000 },
  { mal_id: 10, name: 'Fantasy', count: 2500 },
  { mal_id: 7, name: 'Mystery', count: 900 },
  { mal_id: 22, name: 'Romance', count: 2000 },
  { mal_id: 24, name: 'Sci-Fi', count: 3000 },
  { mal_id: 36, name: 'Slice of Life', count: 1600 },
  { mal_id: 30, name: 'Sports', count: 700 },
  { mal_id: 37, name: 'Supernatural', count: 1400 },
  { mal_id: 41, name: 'Suspense', count: 300 },
  { mal_id: 14, name: 'Horror', count: 500 },
  { mal_id: 25, name: 'Shoujo', count: 800 },
  { mal_id: 27, name: 'Shounen', count: 1800 },
  { mal_id: 42, name: 'Seinen', count: 1200 },
  { mal_id: 43, name: 'Josei', count: 400 },
  { mal_id: 19, name: 'Music', count: 400 },
];

export function getMockTopAnime(page: number, limit: number, filter?: string): any {
  let list = [...mockAnimeList];
  if (filter === 'airing') {
    list = list.filter(a => a.status === 'Currently Airing' || Math.random() > 0.4);
  }
  list.sort((a, b) => (a.rank ?? 9999) - (b.rank ?? 9999));
  const start = (page - 1) * limit;
  const paged = list.slice(start, start + limit);
  return {
    data: paged,
    pagination: {
      last_visible_page: Math.ceil(list.length / limit),
      has_next_page: start + limit < list.length,
      current_page: page,
      items: { count: paged.length, total: list.length, per_page: limit },
    },
  };
}

export function getMockAnimeById(id: number): any {
  return mockAnimeList.find(a => a.mal_id === id) || null;
}

export function getMockSearchResults(query: string, page: number, limit: number): any {
  const q = query.toLowerCase();
  const filtered = mockAnimeList.filter(
    a =>
      a.title.toLowerCase().includes(q) ||
      (a.title_english && a.title_english.toLowerCase().includes(q)) ||
      (a.title_japanese && a.title_japanese.includes(q)) ||
      (a.synopsis && a.synopsis.toLowerCase().includes(q)),
  );
  const start = (page - 1) * limit;
  const paged = filtered.slice(start, start + limit);
  return {
    data: paged,
    pagination: {
      last_visible_page: Math.ceil(filtered.length / limit),
      has_next_page: start + limit < filtered.length,
      current_page: page,
      items: { count: paged.length, total: filtered.length, per_page: limit },
    },
  };
}

export function getMockAnimeByGenre(genreId: number, page: number, limit: number): any {
  const filtered = mockAnimeList.filter(a => a.genres.some(g => g.mal_id === genreId));
  const start = (page - 1) * limit;
  const paged = filtered.slice(start, start + limit);
  return {
    data: paged,
    pagination: {
      last_visible_page: Math.ceil(filtered.length / limit),
      has_next_page: start + limit < filtered.length,
      current_page: page,
      items: { count: paged.length, total: filtered.length, per_page: limit },
    },
  };
}

export function getMockGenres(): any {
  return { data: mockGenres };
}

export function getMockSeasonNow(page: number, limit: number): any {
  return getMockTopAnime(page, limit, 'airing');
}
